# Dockerfile
FROM node:22

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Install app dependencies
COPY package*.json ./
RUN npm install
RUN npm install axios

# Copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# Start the application
CMD ["npm", "run", "serve"]